source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

target 'Coins' do
  pod 'HockeySDK'
  pod 'SSPullToRefresh'
  pod 'Localytics-iOS-Client'
end

post_install do |installer|
  require 'fileutils'
  dest = 'Coins/Resources/Settings.bundle/Acknowledgements.plist'
  FileUtils.cp_r('Pods/Target Support Files/Pods-Coins/Pods-Coins-acknowledgements.plist', dest, :remove_destination => true)

  # Strip CocoaPods
  strip = /<dict>\n\t\t\t<key>FooterText<\/key>\n\t\t\t<string>Generated by CocoaPods - http:\/\/cocoapods.org<\/string>\n\t\t\t<key>Title<\/key>\n\t\t\t<string><\/string>\n\t\t\t<key>Type<\/key>\n\t\t\t<string>PSGroupSpecifier<\/string>\n\t\t<\/dict>\n/
  text = File.read(dest).sub(strip, '')
  File.open(dest, 'w') {|file| file.puts text}
end
