platform :ios, '7.0'

pod 'SAMCache'
pod 'SAMGradientView'
pod 'SSPullToRefresh'

pod 'Localytics-iOS-Client'

post_install do |installer|
  require 'fileutils'
  dest = 'Resources/Settings.bundle/Acknowledgements.plist'
  FileUtils.cp_r('Pods/Pods-Acknowledgements.plist', dest, :remove_destination => true)

  # Strip CocoaPods
  strip = /<dict>\n\t\t\t<key>FooterText<\/key>\n\t\t\t<string>Generated by CocoaPods - http:\/\/cocoapods.org<\/string>\n\t\t\t<key>Title<\/key>\n\t\t\t<string><\/string>\n\t\t\t<key>Type<\/key>\n\t\t\t<string>PSGroupSpecifier<\/string>\n\t\t<\/dict>\n/
  text = File.read(dest).sub(strip, '')
  File.open(dest, 'w') {|file| file.puts text}
end
